### ISSUE TITLE
🚀 Roadmap

### ISSUE THREAD

**Issue by felipbizz** [felipbizz/mle-tech-challenge-4#1]
# Descrição
Aqui nesse roadmap você encontra as tarefas que devem ser desenvolvidas para finalizar o desafio.

 ---

## 1. Coleta e Pré-processamento dos Dados

- [x] Coleta de Dados:

 ---

## 2. Desenvolvimento do Modelo LSTM

- [x] Construção do Modelo:
- [x] Treinamento:
- [x] Avaliação:

 ---

## 3. Salvamento e Exportação do Modelo

- [x] Salvar o Modelo:

 ---

## 4. Deploy do Modelo

- [x] Criação da API:

 ---

## 5. Escalabilidade e Monitoramento

- [ ] Monitoramento:

 ---

# Entregáveis:

- [ ] Código-fonte do modelo LSTM no repositório do GIT:
- [ ] Documentação do projeto.
- [ ] Scripts ou contêineres Docker para deploy da API.
- [ ] Link para a API em produção, caso tenha sido deployada em um
ambiente de nuvem.
- [ ] Vídeo mostrando e explicando todo o funcionamento da API.

Prazo: 18/02
